 export const user = {
    name: 'Le Parc De Goûts',
    siret: 12345678987451,
    phone: '06.70.00.93.08',
    email: 'leparcdegouts@orange.fr',
    website: 'le-parc-de-gouts.fr',
    adress: {
        number: 1,
        street: 'parc de goûts',
        zipcode: 47190,
        city: "Aiguillon",
    },
    openAudit: [
        {
            firstname: "Adrien", 
            name: "Weissenbacher",
            date: '18/12/2023',
            adress: {
                number: 42,
                street: "avenue Emile Roudayre",
                zipcode: 66000,
                city: "Perpignan",
                country: "France"
            },            
            pieces: [
                { 
                     name: "Piscine",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",              
                 },
                 { 
                     name: "Poolhouse",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",      
                 },
                 { 
                     name: "Salon",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",                    
                 },
                 { 
                     name: "Buanderie",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",        
                 },
                 { 
                     name: "Cuisine",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",     
                 },
                 { 
                     name: "Chambre 1",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",           
                 },
                 { 
                     name: "Chambre 2",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",     
                 },
                 { 
                     name: "Salle de bain 1",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",     
                 },
                 { 
                     name: "Chambre 3",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",     
                 },
                 { 
                     name: "Salle bain 2",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",       
                 },
                 { 
                     name: "Chambre 4",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",       
                 },
                 { 
                     name: "Salle de bain 3",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",       
                 },
                 { 
                     name: "Chambre 5",
                     sol: "Très bon",
                     meubles: "Bon",
                     plafond: "Bon",
                     electricity: "Bon",
                     exitSol: "",
                     exitMeubles: "",
                     exitPlafond: "",
                     exitElectricity: "",
                     plafondComment: "", 
                     electricityComment: "", 
                     solComment: "",
                     meublesComment: "",       
                 },
            ]
        }
             
    ],
    closeAudit: [
        {
            firstname: "Joe", 
            name: "Doe",
            date: '18/12/2023',
            departure: '25/12/2023',
            adress: {
                number: 42,
                street: "avenue Emile Roudayre",
                zipcode: 66000,
                city: "Perpignan",
                country: "France"
            },            
            pieces: [
               { 
                    name: "Piscine",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",              
                },
                { 
                    name: "Poolhouse",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Salon",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",               
                },
                { 
                    name: "Buanderie",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",  
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",   
                },
                { 
                    name: "Cuisine",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",                    
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Chambre 1",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",        
                },
                { 
                    name: "Chambre 2",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",  
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Salle de bain 1",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Chambre 3",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",  
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Salle bain 2",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",  
                },
                { 
                    name: "Chambre 4",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",   
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",   
                },
                { 
                    name: "Salle de bain 3",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",  
                },
                { 
                    name: "Chambre 5",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",  
                },

            ],         
        },
        {
            firstname: "Adrien", 
            name: "De Vengerberg",
            date: '18/12/2023',
            departure: '25/12/2023',
            adress: {
                number: 42,
                street: "avenue Emile Roudayre",
                zipcode: 66000,
                city: "Perpignan",
                country: "France"
            },            
            pieces: [
               { 
                    name: "Piscine",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",              
                },
                { 
                    name: "Poolhouse",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Salon",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",               
                },
                { 
                    name: "Buanderie",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",  
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",   
                },
                { 
                    name: "Cuisine",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",                    
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Chambre 1",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",        
                },
                { 
                    name: "Chambre 2",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",  
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Salle de bain 1",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Chambre 3",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",  
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé", 
                },
                { 
                    name: "Salle bain 2",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon", 
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",  
                },
                { 
                    name: "Chambre 4",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",   
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",   
                },
                { 
                    name: "Salle de bain 3",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",  
                },
                { 
                    name: "Chambre 5",
                    sol: "Très bon",
                    meubles: "Bon",
                    plafond: "Bon",
                    electricity: "Bon",
                    exitSol: "Très bon",
                    exitMeubles: "Bon",
                    exitPlafond: "Bon",
                    exitElectricity: "Bon",
                    plafondComment: "Plafond abîmé", 
                    electricityComment: "Prise arrachée", 
                    solComment: "Sol arrachée",
                    meublesComment: "Meuble abimé",  
                },                
            ],         
        },             
    ],
}